module.exports = [
  'el',
  'name',
  'key',
  'parent',
  'functional',
  ['delimiters', 'comments'],
  ['components', 'directives', 'filters'],
  'extends',
  'mixins',
  ['provide', 'inject'],
  'ROUTER_GUARDS',
  'layout',
  'middleware',
  'validate',
  'scrollToTop',
  'transition',
  'loading',
  'inheritAttrs',
  'model',
  ['props', 'propsData'],
  'emits',
  'setup',
  'asyncData',
  'data',
  'fetch',
  'head',
  'computed',
  'watch',
  'watchQuery',
  'LIFECYCLE_HOOKS',
  'methods',
  ['template', 'render'],
  'renderError',
]